services:
  
  cloud-sql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.20.0
    command:
      - "${PROJECT_ID}:${LOCATION}:${INSTANCE_NAME}"
      - "--address=0.0.0.0"
      - "--port=5432"
      - "--credentials-file=/app/credentials.json"
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    networks:
      - rehab-network

  app:
    build:
      context: ./elbow_rehab/service
      dockerfile: Dockerfile
    depends_on:
      - cloud-sql-proxy
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials.json
    networks:
      - rehab-network


networks:
  rehab-network:
    driver: bridge